services:
  app:
    image: env-side
    privileged: true
    tty: true
    build:
      context: ./
      args:
        environment: development
    ports:
      - "3001:3000"
      - "8001:8000"
    volumes:
      - ~/code:/root/code
      - ~/.ssh:/root/.ssh:ro
    command: /bin/bash

