services:
  env-side:
    privileged: true
    tty: true
    build:
      context: ./
      args:
        environment: development
    ports:
      - "3003:3000"
    volumes:
      - ~/code:/root/code
    command: /bin/bash

